### ISSUE TITLE
Does not work with UIView on iOS 15

### ISSUE THREAD

**Issue by kuzomenskyi** [imjog/AnimatedMaskLabel#34]
**Actual Behaviour**
No animation displayed after calling 
LoadingShimmer.startCovering(view, with: nil)

**Expected Behaviour**
Animation displayed

**Steps to reproduce it**
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let animationView = UIView()
        view.addSubviews(animationView)
        
        animationView.snp.makeConstraints {
            $0.edges.equalToSuperview()
        }
        
        LoadingShimmer.startCovering(animationView, with: nil)
    }

**LogCat for the issue**

No crash there

Clear view. Changing backgroundColor of the view has no affect

**Would you like to work on the issue?**

Maybe

**Comment by narendrajagne** [comment]
His, Can you assign me this issue ?

**Comment by kuzomenskyi** [comment]
> His, Can you assign me this issue ?

Hi! I have no permission to do that. I will close the issue and you can open it yourself
